title: Hangqian Li | Neil
url: "https://neilgogogo.github.io"
baseurl: "/neil"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/neilgogogo"
footer_text: "Page design by Neil"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/neil/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"

